
/*
CHALLENGE 039 — Total Revenue by Customer

Goal:
Calculate the total revenue generated by each customer.

Instructions:
1) Query the tables:
   - customer
   - invoice
2) Join customer to invoice using:
   - customer.customer_id = invoice.customer_id
3) Group rows by:
   - customer.customer_id
   - customer.first_name
   - customer.last_name
4) Compute:
   - SUM(invoice.total) AS total_revenue
5) Select exactly these columns (in this order):
   - customer_id
   - first_name
   - last_name
   - total_revenue
6) Filter groups where:
   - SUM(invoice.total) >= 40.00
7) Sort the result by:
   - total_revenue DESC
   - customer_id ASC

Expected:
A result set with 4 columns:
customer_id, first_name, last_name, total_revenue
Only customers with total revenue of at least 40.00, ordered by total_revenue descending and customer_id ascending.
*/
