
/*
CHALLENGE 044 — Total Revenue by Album

Goal:
Calculate total revenue generated by each album.

Instructions:
1) Query the tables:
   - invoice_line
   - track
   - album
2) Join tables using:
   - invoice_line.track_id = track.track_id
   - track.album_id = album.album_id
3) Group rows by:
   - album.album_id
   - album.title
4) Compute:
   - SUM(invoice_line.unit_price * invoice_line.quantity) AS total_revenue
5) Select exactly these columns (in this order):
   - album.title AS album_title
   - total_revenue
6) Filter groups where:
   - SUM(invoice_line.unit_price * invoice_line.quantity) >= 100.00
7) Sort the result by:
   - total_revenue DESC
   - album.title ASC

Expected:
A result set with 2 columns:
album_title, total_revenue
Only albums with total_revenue >= 100.00, ordered by total_revenue descending and album_title ascending.
*/
