
-- CHALLENGE 042 - TOTAL SALES PER ARTIST
-- Difficulty: MEDIUM
-- Topic: GROUP BY + SUM
-- Database: Chinook

-- DESCRIPTION:
-- Calculate the total revenue generated by each artist.
-- This challenge focuses on joining multiple tables and summing invoice line amounts.

-- REQUIREMENTS:
--   1. Select the following columns:
--        - Artist.Name AS ArtistName
--        - SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS TotalSales
--   2. Join Artist → Album using ArtistId.
--   3. Join Album → Track using AlbumId.
--   4. Join Track → InvoiceLine using TrackId.
--   5. Group results by ArtistName.
--   6. Sort results by TotalSales in descending order.

SELECT
    ar.Name AS ArtistName,
    SUM(il.UnitPrice * il.Quantity) AS TotalSales
FROM Artist AS ar
INNER JOIN Album AS al
    ON al.ArtistId = ar.ArtistId
INNER JOIN Track AS t
    ON t.AlbumId = al.AlbumId
INNER JOIN InvoiceLine AS il
    ON il.TrackId = t.TrackId
GROUP BY
    ar.Name
ORDER BY
    TotalSales DESC;