
-- CHALLENGE 040 - TOTAL INVOICE COUNT PER CUSTOMER
-- Difficulty: MEDIUM
-- Topic: GROUP BY + COUNT
-- Database: Chinook

-- DESCRIPTION:
-- Retrieve the number of invoices generated by each customer.
-- This challenge focuses on counting grouped records.

-- REQUIREMENTS:
--   1. Select the following columns:
--        - Customer.CustomerId
--        - Customer.FirstName
--        - Customer.LastName
--        - COUNT(Invoice.InvoiceId) AS InvoiceCount
--   2. Join Customer → Invoice using CustomerId.
--   3. Group results by:
--        - Customer.CustomerId
--        - Customer.FirstName
--        - Customer.LastName
--   4. Sort the results by InvoiceCount in descending order.

SELECT
    c.CustomerId,
    c.FirstName,
    c.LastName,
    COUNT(i.InvoiceId) AS InvoiceCount
FROM Customer c
JOIN Invoice i
    ON c.CustomerId = i.CustomerId
GROUP BY
    c.CustomerId,
    c.FirstName,
    c.LastName
ORDER BY
    InvoiceCount DESC;
