
-- CHALLENGE 042 - TOTAL SALES PER ARTIST
-- Difficulty: MEDIUM
-- Topic: GROUP BY + SUM
-- Database: Chinook

-- DESCRIPTION:
-- Calculate the total revenue generated by each artist.
-- This challenge focuses on joining multiple tables and summing invoice line amounts.

-- REQUIREMENTS:
--   1. Select the following columns:
--        - Artist.Name AS ArtistName
--        - SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS TotalSales
--   2. Join Artist → Album using ArtistId.
--   3. Join Album → Track using AlbumId.
--   4. Join Track → InvoiceLine using TrackId.
--   5. Group results by ArtistName.
--   6. Sort results by TotalSales in descending order.
