
/*
CHALLENGE 042 — Total Revenue by Genre

Goal:
Calculate total revenue generated by each genre.

Instructions:
1) Query the tables:
   - invoice_line
   - track
   - genre
2) Join tables using:
   - invoice_line.track_id = track.track_id
   - track.genre_id = genre.genre_id
3) Group rows by:
   - genre.genre_id
   - genre.name
4) Compute:
   - SUM(invoice_line.unit_price * invoice_line.quantity) AS total_revenue
5) Select exactly these columns (in this order):
   - genre.name AS genre_name
   - total_revenue
6) Filter groups where:
   - SUM(invoice_line.unit_price * invoice_line.quantity) >= 100.00
7) Sort the result by:
   - total_revenue DESC
   - genre.name ASC

Expected:
A result set with 2 columns:
genre_name, total_revenue
Only genres with total_revenue >= 100.00, ordered by total_revenue descending and genre_name ascending.
*/
