
-- CHALLENGE 055 - TOTAL SALES PER GENRE
-- Difficulty: MEDIUM
-- Topic: GROUP BY + SUM
-- Database: Chinook

-- DESCRIPTION:
-- Calculate total sales generated by each music genre.
-- This challenge focuses on joining multiple tables and aggregating revenue.

-- REQUIREMENTS:
--   1. Select the following columns:
--        - Genre.Name AS GenreName
--        - SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS TotalSales
--   2. Join Genre → Track using GenreId.
--   3. Join Track → InvoiceLine using TrackId.
--   4. Group results by GenreName.
--   5. Sort results by TotalSales in descending order.

SELECT
    Genre.Name AS GenreName,
    SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS TotalSales
FROM Genre
JOIN Track
    ON Genre.GenreId = Track.GenreId
JOIN InvoiceLine
    ON Track.TrackId = InvoiceLine.TrackId
GROUP BY Genre.Name
ORDER BY TotalSales DESC;
