
/*
CHALLENGE 043 — Total Revenue by Artist

Goal:
Calculate total revenue generated by each artist.

Instructions:
1) Query the tables:
   - invoice_line
   - track
   - album
   - artist
2) Join tables using:
   - invoice_line.track_id = track.track_id
   - track.album_id = album.album_id
   - album.artist_id = artist.artist_id
3) Group rows by:
   - artist.artist_id
   - artist.name
4) Compute:
   - SUM(invoice_line.unit_price * invoice_line.quantity) AS total_revenue
5) Select exactly these columns (in this order):
   - artist.name AS artist_name
   - total_revenue
6) Filter groups where:
   - SUM(invoice_line.unit_price * invoice_line.quantity) >= 200.00
7) Sort the result by:
   - total_revenue DESC
   - artist.name ASC

Expected:
A result set with 2 columns:
artist_name, total_revenue
Only artists with total_revenue >= 200.00, ordered by total_revenue descending and artist_name ascending.
*/
